<a href="https://colab.research.google.com/github/Ria-varsha/Data-visualization/blob/main/data_pre_processing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd

In [4]:
from google.colab import files
uploaded = files.upload()

Saving tourism_exact_190_raw.csv to tourism_exact_190_raw.csv

In [6]:
df = pd.read_csv("tourism_exact_190_raw.csv")

In [7]:
df.head()
df.shape
df.columns

Index(['Continent', 'Country', 'City', 'Arrivals_2019', 'Arrivals_2022',
       'Arrivals_2023', 'ISO'],
      dtype='object')

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 190 entries, 0 to 189
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Continent      190 non-null    object
 1   Country        190 non-null    object
 2   City           186 non-null    object
 3   Arrivals_2019  190 non-null    float64
 4   Arrivals_2022  190 non-null    float64
 5   Arrivals_2023  190 non-null    float64
 6   ISO            190 non-null    object
dtypes: float64(3), object(4)
memory usage: 10.5+ KB

In [9]:
df.isnull().sum()

Continent        0
Country          0
City             4
Arrivals_2019    0
Arrivals_2022    0
Arrivals_2023    0
ISO              0
dtype: int64

In [10]:
df = df.dropna(subset=["Country", "ISO", "Continent"])
df = df.fillna(0)

In [12]:
print(df.columns)

Index(['Continent', 'Country', 'City', 'Arrivals_2019', 'Arrivals_2022',
       'Arrivals_2023', 'ISO'],
      dtype='object')

In [13]:
df["Arrivals_2019"] = pd.to_numeric(df["Arrivals_2019"], errors="coerce")
df["Arrivals_2023"] = pd.to_numeric(df["Arrivals_2023"], errors="coerce")

In [14]:
df = df[df["Arrivals_2019"] > 0]

In [15]:
df["pct_growth"] = ((df["Arrivals_2023"] - df["Arrivals_2019"]) / df["Arrivals_2019"]) * 100

In [16]:
df["pct_growth"] = df["pct_growth"].round(1)

In [17]:
df = df.drop_duplicates(subset=["ISO"])

In [18]:
df["Country"] = df["Country"].str.strip()
df["Continent"] = df["Continent"].str.strip()
df["ISO"] = df["ISO"].str.strip().str.upper()

In [19]:
df_clean = df[["Country", "ISO", "Continent", "pct_growth"]]

In [20]:
df_clean.head()
df_clean.shape
df_clean.describe()

       pct_growth
count   34.000000
mean     5.197059
std     17.337741
min    -29.200000
25%     -6.800000
50%      4.900000
75%     20.225000
max     29.700000

In [21]:
df_clean.to_csv("tourism_cleaned.csv", index=False)